apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voting-app.fullname" . }}-config
  namespace: {{ .Values.namespace | default "voting-app" }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
data:
  OPTION_A: {{ .Values.config.optionA | quote }}
  OPTION_B: {{ .Values.config.optionB | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}

