apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-app-config
  namespace: voting-app
data:
  OPTION_A: "Cats"
  OPTION_B: "Dogs"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  REDIS_HOST: "redis-service"
  POSTGRES_HOST: "postgres-service"

