apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - vote-deployment.yaml
  - result-deployment.yaml
  - worker-deployment.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - network-policies.yaml
  - ingress.yaml

