apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-app-sa
  namespace: voting-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: voting-app
  name: voting-app-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voting-app-rolebinding
  namespace: voting-app
subjects:
- kind: ServiceAccount
  name: voting-app-sa
  namespace: voting-app
roleRef:
  kind: Role
  name: voting-app-role
  apiGroup: rbac.authorization.k8s.io

